### ISSUE TITLE
Outdated barebones

### ISSUE THREAD

**Issue by DarkoniusXNG** [LoopyAshy/Better-Dota-Butts#1]
Hi. I noticed you are using outdated BMD barebones. I am the guy that made a new (simpler?) barebones based on BMD one. I am creating this issue to point out stuff that doesn't work.

SetRuneSpawnTime does nothing: https://github.com/LoopyAshy/Better-Dota-Butts/blob/master/Main/game/scripts/vscripts/internal/gamemode.lua#L17

SetCustomHeroMaxLevel does nothing: https://github.com/LoopyAshy/Better-Dota-Butts/blob/master/Main/game/scripts/vscripts/internal/gamemode.lua#L146

SetSafeToLeave is useless: https://github.com/LoopyAshy/Better-Dota-Butts/blob/master/Main/game/scripts/vscripts/internal/events.lua#L59

SetRemoveIllusionsOnDeath doesn't work too: https://github.com/LoopyAshy/Better-Dota-Butts/blob/master/Main/game/scripts/vscripts/internal/gamemode.lua#L156

For using default runes and default rune timings use this: https://github.com/DarkoniusXNG/barebones/blob/source2/game/dota_addons/barebones/scripts/vscripts/gamemode.lua#L331
gamemode:SetUseDefaultDOTARuneSpawnLogic(true)

For using different rune timings there are:
gamemode:SetBountyRuneSpawnInterval(BOUNTY_RUNE_SPAWN_INTERVAL)
gamemode:SetPowerRuneSpawnInterval(POWER_RUNE_SPAWN_INTERVAL)

For custom Strategy and Showcase time there are: 
GameRules:SetShowcaseTime(SHOWCASE_TIME)
GameRules:SetStrategyTime(STRATEGY_TIME)

**Comment by DarkoniusXNG** [comment]
Here is a link to my barebones: https://github.com/DarkoniusXNG/barebones/tree/source2/game/dota_addons/barebones/scripts/vscripts
Maybe it will help you improve this dota butt base boilerplate.

**Comment by LoopyAshy** [comment]
Thank you greatly for this information, my latest update should hopefully resolve the issues but will do more work to it in future.
